management:
  endpoint:
    configprops:
      show-values: always
    env:
      show-values: always
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'          
server:
  port: 8080
spring:
  application:
    name: nacos-actions
  cloud:
    nacos:
      discovery:
        namespace: public
        password: 535177972
        server-addr: 119.3.223.16:8848
        username: nacos
