server:
  port: 8080
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
spring:
  application:
    name: nacos-native
  cloud:
    nacos:
      discovery:
        namespace: public
        password: 535177972
        server-addr: 47.57.68.189:8848
        username: nacos