name: Docker Image CI
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build the Docker image
        run: |
          docker version
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME_ALIYUN }} --password=${{ secrets.DOCKER_PASSWORD_ALIYUN }} registry.cn-hongkong.aliyuncs.com
          pwd
          # 使用Dockerfile构建镜像
          docker build . --file Dockerfile --tag registry.cn-hongkong.aliyuncs.com/karl-chanel/demo-actions:v1.0.0
          # 推送镜像到镜像仓库
          docker push registry.cn-hongkong.aliyuncs.com/karl-chanel/demo-actions:v1.0.0